.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONSOLE" "1" "February 2013" "" ""
.
.SH "NAME"
\fBconsole\fR \- test program for console(3)
.
.SH "SYNOPSIS"
.
.nf

console [options] message [replacements\.\.\.]
.
.fi
.
.SH "DESCRIPTION"
Test program for console(3) and sprintf(3)\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-color=[auto|never|always]\fR:

.
.P
Sets the environment variable for sprintf(3) that overrides any \fB\-\-color\fR options passed to sprintf(3)\.
.
.TP
\fB\-\-debug\fR:

.
.P
Set \fB\-x\fR\.
.
.TP
\fB\-\-printf\fR:

.
.P
Only invoke the printf tests\.
.
.SH "USAGE"
When invoked with no options this program prints a series of test messages\. When options are specified they are passed on to sprintf(3)\.
.
.SH "EXAMPLES"
Print test messages:
.
.IP "" 4
.
.nf

console
.
.fi
.
.IP "" 0
.
.P
Print test messages with no color:
.
.IP "" 4
.
.nf

console \-\-color=never
.
.fi
.
.IP "" 0
.
.P
Print test messages with color set to \fIalways\fR overriding sprintf(3) \fB\-\-color=never\fR option in tests:
.
.IP "" 4
.
.nf

console \-\-color=always
.
.fi
.
.IP "" 0
.
.P
Pipe to \fBless\fR with color:
.
.IP "" 4
.
.nf

console \-\-color=always 2>&1 | less \-R
.
.fi
.
.IP "" 0
.
.P
Pipe to \fBless\fR with no color:
.
.IP "" 4
.
.nf

console \-\-color=never 2>&1 | less
.
.fi
.
.IP "" 0
.
.P
Pipe to \fBcat\fR with color:
.
.IP "" 4
.
.nf

console \-\-color=always 2>&1 | cat
.
.fi
.
.IP "" 0
.
.P
Pipe to \fBcat\fR with no color:
.
.IP "" 4
.
.nf

console \-\-color=never 2>&1 | cat
.
.fi
.
.IP "" 0
.
.P
Redirect output to a file with no color:
.
.IP "" 4
.
.nf

console \-\-color=never > console\.log 2>&1
.
.fi
.
.IP "" 0
.
.P
Show the console(3) manual:
.
.IP "" 4
.
.nf

console help console
.
.fi
.
.IP "" 0
.
.P
Show the sprintf(3) manual:
.
.IP "" 4
.
.nf

console help sprintf
.
.fi
.
.IP "" 0
.
.P
Show this manual:
.
.IP "" 4
.
.nf

console help
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBconsole\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBconsole\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
console(3), sprintf(3)
