.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONSOLE" "3" "February 2013" "" ""
.
.SH "NAME"
\fBconsole\fR \- console module
.
.SH "SYNOPSIS"
.
.nf

console [command] [options\.\.\.] message [parameters\.\.\.]
.
.fi
.
.SH "DESCRIPTION"
Helper commands for printing ANSI formatted output to a terminal\.
.
.P
The console(3) module is a built in module available to all programs\. It is responsible for printing messages with optional replacement parameters which are highlighted when the message is printed\.
.
.SH "COMMANDS"
.
.SS "Standard Output"
To print to standard output use the following commands:
.
.TP
\fBprint\fR:
.
.IP
Print a message with no prefix\.
.
.TP
\fBinfo\fR:
.
.IP
Print an info message\.
.
.TP
\fBlog\fR:
.
.IP
Print a log message\.
.
.TP
\fBok\fR:
.
.IP
Print an ok message\. This message type appends a suffix of ✓ (\eu2713)\.
.
.TP
\fBprompt\fR:
.
.IP
Create a message suitable for passing to \fBread \-ep\fR and assign the result to the \fBPS9\fR variable\.
.
.SS "Standard Error"
To print to standard error use the following commands:
.
.TP
\fBwarn\fR:
.
.IP
Print a warning message\.
.
.TP
\fBerror\fR:
.
.IP
Print an error message\.
.
.TP
\fBnotok\fR:
.
.IP
Print a not ok message\. This message type appends a suffix of ✘ (\eu2718)\.
.
.TP
\fBthrow\fR:
.
.IP
Print an error message followed by a stack trace of the current command call stack\.
.
.SS "Exit Commands"
The console(3) module provides commands for exiting the program (optionally with a formatted message)\.
.
.TP
\fBsuccess\fR:
.
.IP
Marks the program as completed successfully (exiting with a zero exit code) and optionally prints a formatted message\.
.
.TP
\fBquit\fR:
.
.IP
Exits the program with a non\-zero exit code and optional error message\. Note that the signature for this method differs from the general syntax for console(3) methods as it expects the first parameter to be the exit code\.
.
.SH "OPTIONS"
The console(3) module supports all the options available to the sprintf(3) module\.It is recommended that users of iTerm2 uncheck the \fBDraw bold text in bright colors\fR option in \fBProfiles > Text\fR for highlighted replacement values to appear consistently with the main message colour\.
.
.SH "BUGS"
\fBconsole\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBconsole\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
sprintf(3), globals\-api(3)
