.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EXECUTABLE" "7" "December 2012" "" ""
.
.SH "NAME"
\fBexecutable\fR \- executable module
.
.SH "SYNOPSIS"
Module methods for system executables\.
.
.SH "DESCRIPTION"
Enables validation and referencing of executables in \fB$PATH\fR\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBexecutable\fR module using:
.
.IP "" 4
.
.nf

require \'executable\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
Once the module is available you can then validate a list of executables:
.
.IP "" 4
.
.nf

executable validate ronn git;
.
.fi
.
.IP "" 0
.
.P
If any of the listed executables are not available on the system the program will exit with a non\-zero exit code\. If executable validation succeeds the executable paths are available in the global \fBexecutables\fR associative array and can be accessed anywhere in the program, for example:
.
.IP "" 4
.
.nf

local git="${executables[git]}";
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBexecutable\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBexecutable\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
require(7)
