.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GLOBALS" "3" "March 2013" "" ""
.
.SH "NAME"
\fBglobals\fR \- global variables
.
.SH "VARIABLES"
.
.TP
\fBframework\fR:

.
.P
Constant representing the framework name\.
.
.SS "PROGRAM"
.
.TP
\fBprogram_options\fR:

.
.P
A duplicate of the original program options\.
.
.TP
\fBprocess_name\fR:

.
.P
Store the program name for better code legibilty\.
.
.TP
\fBlibrary_dirs\fR:

.
.P
Directories for the library code\.
.
.TP
\fBprocess_dirs\fR:

.
.P
Directories for the current program\.
.
.SS "OPTIONS"
See options(3) for related information\.
.
.TP
\fBglobal_options\fR:

.
.P
A list of global options that modules may inspect to control functionality for all programs\. Modules that do so \fIshould\fR not modify the options passed to the program but program option parsing may want to shift or ignore these options (as they have already been handled) therefore they are listed here\.
.
.SS "EXECUTABLE"
See executable(3) for related information\.
.
.TP
\fBexecutables\fR:

.
.P
Associative array of executable paths created by executable(3)\.
.
.SS "CONSOLE"
See console(3) for related information\.
.
.TP
\fBconsole_prefixes\fR:

.
.P
Associative array of prefixes used by console(3) methods\.
.
.SS "REQUIRE"
See require(3) for related information\.
.
.TP
\fBmodule_paths\fR:

.
.P
Associative array of loaded modules\. Each key is the absolute filesystem path to the module file and the value is the extracted module name\.
.
.SH "SEE ALSO"
executable(3), console(3), require(3)
