.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JSON" "3" "January 2013" "" ""
.
.SH "NAME"
\fBjson\fR \- JSON manipulation
.
.SH "SYNOPSIS"
An experimental module for parsing and stringifying JSON data\.
.
.SH "DESCRIPTION"
The json(3) module adds methods for parsing and creating JSON documents\.
.
.SH "USAGE"
Parsing JSON data can be from a file, string or variable\. After parsing the JSON data the parsed data is available on the global \fBjson_doc\fR associative array\. Use the \fBjson\.print\fR method to quickly inspect the contents of the parsed data\.
.
.IP "" 4
.
.nf

require \'json\';

# parse a json document
json\.parse < "${process_dirs[root]}/package\.json";
json\.print;

# parse a json string
json\.parse <<< \'{ "data": "value" }\';
json\.print;

# clean up parsed json data
json\.clean;
.
.fi
.
.IP "" 0
.
.P
Converting to JSON is achieved using references to variable names and afterwards the JSON string is available in the global \fBjson_str\fR variable\. Use the \fBjson\.string\fR method to print the JSON string data\.
.
.IP "" 4
.
.nf

require \'json\';

toJSON() {
    declare \-A doc;
    doc[key]="value";
    doc[greeting]="hello world";
    # doc is the *name* of the variable to stringify
    json\.stringify <<< "doc";
    # print the result
    json\.string;
}
toJSON;
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBjson\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.P
The json(3) module is derived from json\-sh(1)\.
.
.SH "COPYRIGHT"
\fBjson\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
strike(7)
