.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PROMPT" "3" "February 2013" "" ""
.
.SH "NAME"
\fBprompt\fR \- user input module
.
.SH "SYNOPSIS"
.
.nf

prompt [command] [options\.\.\.]
.
.fi
.
.SH "DESCRIPTION"
Captures user input using \fBread\fR\.
.
.SH "COMMANDS"
.
.TP
\fBconfirm\fR:

.
.P
Capture a boolean response, this is useful for confirmation prompts\. By default, the values \fIyes\fR and \fIno\fR are used as the strings for comparison as to whether the confirmation was accepted or rejected\. Comparison is done in a case\-insensitive comparison on the first character of the received input\.
.
.TP
\fBvalue\fR:

.
.P
Capture a non\-empty string value\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-id=[identifier]\fR:

.
.P
Associate \fIid\fR with a prompt\.
.
.TP
\fB\-\-hist\-file=[file]\fR:

.
.P
Use \fIfile\fR for the history file\. If this option is not specified no history is maintained, if \fIfile\fR does not exist it is created\.
.
.SH "BUGS"
\fBprompt\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBprompt\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
prompt(1)
