.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "REQUIRE" "3" "December 2012" "" ""
.
.SH "NAME"
\fBrequire\fR \- module loader
.
.SH "SYNOPSIS"
Module loader for strike(7)\.
.
.SH "DESCRIPTION"
Loads modules by name and relative or absolute filesystem paths\.
.
.SH "USAGE"
.
.nf

require \'module\';
require \'\./module\';
require \'/path/to/module\';
.
.fi
.
.SH "BUGS"
\fBrequire\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBrequire\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
strike(7)
