.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RLX" "1" "January 2013" "" ""
.
.SH "NAME"
\fBrlx\fR \- couchdb command line interface
.
.SH "SYNOPSIS"
A command line interface for couchdb(7)\.
.
.SH "DESCRIPTION"
Allows manipulation and querying of couchdb(7) databases from the command line\.
.
.SH "USAGE"
.
.nf

rlx shell [options\.\.\.] [host]
.
.fi
.
.SH "COMMANDS"
.
.TP
\fBshell\fR:
.
.IP
Runs an interactive shell\.
.
.SH "SHELL COMMANDS"
These commands apply when running as an interactive shell\.
.
.TP
\fBdb\fR:
.
.IP
When called with no options, this shell command will list available databases for the current database server\.
.
.TP
\fBdb create [database]\fR:
.
.IP
Create a database with the specified database name\. The database name must match the pattern ^[\-a\-zA\-Z0\-9]+$\.
.
.TP
\fBhelp\fR:
.
.IP
Display this man page\.
.
.TP
\fBquit | exit\fR:
.
.IP
Quit the interactive shell\.
.
.SH "FILES"
The rlx(1) program stores various configuration files in \fB$HOME/\.rlx\fR\.
.
.SS "AUTHENTICATION"
Cached authentication information is stored in \fB$HOME/\.rlx/auth\.json\fR this file is encrypted using AES\-256\-CBC when the program is first run and a valid master password is supplied\.
.
.SS "RESPONSE"
The JSON document containing the last database response is stored in \fB$HOME/\.rlx/log/response\.json\fR\.
.
.SH "DEPENDENCIES"
openssl(1), curl(1), tee(1)
.
.SH "BUGS"
\fBrlx\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBrlx\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
couchdb(3), http(3), json(3), curl(1)
