.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RLX" "1" "January 2013" "" ""
.
.SH "NAME"
\fBrlx\fR \- couchdb command line interface
.
.SH "SYNOPSIS"
A command line interface for couchdb(7)\.
.
.SH "DESCRIPTION"
Allows manipulation and querying of couchdb(7) databases from the command line\.
.
.SH "USAGE"
.
.nf

rlx shell [options\.\.\.] [host]
.
.fi
.
.SH "FILES"
The rlx(1) program stores various configuration files in \fB$HOME/\.rlx\fR\.
.
.SH "DEPENDENCIES"
openssl(1), curl(1), tee(1)
.
.SH "BUGS"
\fBrlx\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBrlx\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
couchdb(3), http(3), json(3), curl(1)
