.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STRIKE\-CREDITS" "7" "December 2012" "" ""
.
.SH "NAME"
\fBstrike\-credits\fR \- credits for strike(7)
.
.SH "SYNOPSIS"
It is my belief that no work is truly original as every creation stands on the shoulders of giants whether the influence is conscious or not\.
.
.P
This work could not have been possible without the excellent work of many other people here I list some of the obvious influences and direct contributions\.
.
.SH "BASH"
None of this would be possible without Brian Fox\'s bash(1)\.
.
.SH "HTTP"
The http(3) module is a wrapper for the excellent curl(1), thanks to Daniel Stenberg and all the other contributors\.
.
.SH "RONN"
Man page documentation thanks to Ryan Tomayko, see ronn(1)\.
.
.SH "JSON"
The json module was based on code by Dominic Tarr, see json\-sh(1)\.
.
.SH "SEE ALSO"
strike(7)
