.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STRIKE" "1" "December 2012" "" ""
.
.SH "NAME"
\fBstrike\fR \- require(3) for bash
.
.SH "SYNOPSIS"
Utility program for inspecting information about the system and bash installation\.
.
.SH "DESCRIPTION"
The strike(1) program also provides debugging commands and the ability to switch the installed bash version\.
.
.SH "COMMANDS"
The strike(1) supports the following commands:
.
.TP
\fBinfo\fR
Print system information\.
.
.TP
\fBpkg\fR
Print npm(1) package information\.
.
.TP
\fBmodule\.dirs\fR
Print a module search path directories\.
.
.TP
\fBmodule\.list\fR
Print a module list\.
.
.TP
\fBmethod\.list\fR
Print method names\.
.
.TP
\fBdirs\fR
Print program directories\.
.
.TP
\fBlib\.dirs\fR
Print library directories\.
.
.SH "BUGS"
\fBstrike\fR is written in bash and depends upon \fBbash\fR >= 4 for associative arrays\.
.
.SH "COPYRIGHT"
\fBstrike\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
