.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-CLEAN" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-clean\fR \- clean task(s) for bake(1)
.
.SH "SYNOPSIS"
Clean task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Removes the \fB${target}\fR directory\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBclean\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/clean\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake clean
.
.fi
.
.SH "BUGS"
\fBtask\-clean\fR is written in bash and depends upon \fBbash\fR >= 4.2\.
.
.SH "COPYRIGHT"
\fBtask\-clean\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
