.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-PROJECT" "7" "March 2013" "" ""
.
.SH "NAME"
\fBtask\-project\fR \- project task(s) for bake(1)
.
.SH "SYNOPSIS"
Project task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Maintains a list of related projects by unique identifier\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBproject\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/project\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake project init
bake project add [flags\.\.\.] [id] [path|url] [url\.\.\.]
bake project exists [id]
bake project ls
bake project count
bake project set [id] [name] [value]
bake project get [id] [name]
bake project del [id] [name\.\.\.]
bake project print [\-\-pretty]
bake project rm [id\.\.\.]
.
.fi
.
.SH "IDENTIFIERS"
Project identifiers must be unique and must consist solely of the hyphen \'\-\' and alphanumeric characters\. They may not contain any other characters\. These rules for project identifiers also apply to meta property names specified using the \fBset\fR command\.
.
.SH "COMMANDS"
.
.TP
\fBinit\fR:
.
.IP
Creates an empty projects file\. This command will exit with >0 exit code if a projects file already exists\.
.
.TP
\fBadd\fR:
.
.IP
Add a project, the first option to this command is the unique identifier for the project the second option is either a relative or absolute file system path to the project or a remote URL\. Subsequent options to \fBadd\fR are related URLs for the project\. Note that when specifying URLs they \fIshould\fR be URL encoded so they do not contain any whitespace (or quoted or escaped correctly)\.
.
.IP
This command will create a projects file if it does not exist and overwrite any existing \fIprojects\.json\fR file\.
.
.IP
If the path specified is a filesystem path then it must point to a valid directory\.
.
.TP
\fBset\fR:
.
.IP
Set a meta data property for a project\. Note that if multiple options are specified after the \fBname\fR option for the \fBvalue\fR then they are concatented into a single \fBvalue\fR using a space character as the delimiter\. If the project property with the specified name exists it is overwritten\.
.
.IP
Attempting to set a property on a non\-existent project will result in an error code >0\.
.
.TP
\fBget\fR:
.
.IP
Get a meta data property for a project\. If no property name is specified all meta data for the project is output\. If no project identifier is specified then all project properties are listed\.
.
.IP
The output of this command is the project identifier than a space followed by the property name (a further space) and finally the property value\.
.
.TP
\fBdel\fR:
.
.IP
Deletes meta data properties for a project\.
.
.TP
\fBls\fR:
.
.IP
List projects\. The output of this command is the identifier followed by the path (or URL) delimited by a space\.
.
.TP
\fBexists\fR:
.
.IP
Determine whether a project with the specified identifier exists\.
.
.TP
\fBcount\fR:
.
.IP
Count the number of projects\. The output of this command is an integer corresponding to the number of projects in the projects file\.
.
.TP
\fBprint\fR:
.
.IP
Print the raw JSON information\.
.
.TP
\fBrm\fR:
.
.IP
Remove project(s) with the specified identifier(s)\.
.
.IP
If any of the project identifiers do not exist this command will exit with a code >0 and no further project identifiers will be processed\.
.
.SH "FLAG OPTIONS"
.
.TP
\fB\-f | \-\-force\fR:
.
.IP
Add a project by force even if a project with the same identifier already exists\.
.
.TP
\fB\-\-pretty\fR:
.
.IP
Use in conjunction with the \fBprint\fR command to pretty print the JSON\.
.
.SH "FILES"
The projects meta information is stored in a file named \fIprojects\.json\fR in the \fB${root}\fR of the current project\.
.
.SH "EXIT CODES"
A >0 exit code indicates failure while a 0 exit code indicates success\.
.
.SH "BUGS"
\fBtask\-project\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBtask\-project\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
