.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-DEPLOY" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-deploy\fR \- deploy task(s) for bake(1)
.
.SH "SYNOPSIS"
Deploy task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Performs a deployment for a project\.
.
.SH "REQUIRE"
You do not need to require(3) this task as it is a builtin task\.
.
.SH "USAGE"
.
.nf

bake deploy [options\.\.\.] [profiles\.\.\.]
.
.fi
.
.SH "PROFILES"
You may specify one or more profiles to deploy after any options\. If no profiles are specified then a deploy is attempted using the \fIdefault\fR profile\.
.
.SH "DEFAULT PROFILE"
The default profile uses a \fIgit\fR deployment type and the current branch and git remote URL for deployment on the remote host\.
.
.SH "STRICT"
The deployment process is strict\. Failure is always assumed and when deploying multiple profiles, failure of a profile to deploy will prevent any subsequent profiles from being processed\.
.
.SH "FILES"
A \fIdeploy\.json\fR file must be present in the root of the project and must be valid JSON\. This file may just contain \'{}\' if you wish to use the \fIdefault\fR profile and configure deployment parameters via environment variables\.
.
.SH "ENVIRONMENT"
.
.TP
\fBbake_deploy_remote\fR:

.
.P
The remote host used for deployment when none is specified in \fIdeploy\.json\fR\.
.
.TP
\fBbake_deploy_shell\fR:

.
.P
The shell used on the remote server, defaults to \fB/bin/sh\fR if none is specified\.
.
.TP
\fBbake_deploy_staging\fR:

.
.P
The directory used on the remote server for staging deployment scripts, default is \fB~/\.deploy\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-d | \-\-descriptor [path]\fR:

.
.P
Sets the \fIdeploy\.json\fR descriptor to use for this deployment\.
.
.TP
\fB\-\-staging [path]\fR:

.
.P
Sets the path to the staging directory\.
.
.TP
\fB\-\-local\fR:

.
.P
Perform a deployment locally\.
.
.TP
\fB\-\-json\fR:

.
.P
Dump all profile configuration settings that would be used by a deployment as a JSON document\. This implies \fB\-\-noop\fR and no deployment is performed\. This is useful to determine what settings would be used when running a deployment\.
.
.TP
\fB\-\-pretty\fR:

.
.P
Use in conjunction with the \fB\-\-json\fR option to pretty print the JSON document\.
.
.TP
\fB\-\-noop\fR:

.
.P
Print commands but do not execute them\.
.
.SH "NOTIFICATIONS"
If the \fIgrowlnotify\fR executable is available then a success or failure notification will be sent using \fIgrowlnotify\fR\.
.
.SH "JSON FORMAT"
The format of the \fIdeploy\.json\fR document is described in the task\-deploy\-json(7) man page, to view this man page run:
.
.IP "" 4
.
.nf

bake help deploy\-json
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
Deploy using the default profile:
.
.IP "" 4
.
.nf

bake deploy
.
.fi
.
.IP "" 0
.
.P
Inspect deployment commands with \fB\-\-noop\fR:
.
.IP "" 4
.
.nf

bake deploy \-\-noop
.
.fi
.
.IP "" 0
.
.P
Deploy the profile \fIstage\fR:
.
.IP "" 4
.
.nf

bake deploy stage
.
.fi
.
.IP "" 0
.
.P
Deploy the profiles \fItest\fR, \fIstage\fR and \fIproduction\fR:
.
.IP "" 4
.
.nf

bake deploy test stage production
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBtask\-deploy\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBtask\-deploy\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1), task\-deploy\-json(7)
