.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-COMPRESS" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-compress\fR \- compress task(s) for bake(1)
.
.SH "SYNOPSIS"
Compression task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Compresses file(s) using gzip(1) and gunzip(1)\. This task is used to compress regular files, if you wish to compress directories use task\-archive(7)\. The primary difference between gzip(1) and task\-compress(7) is that source files or compressed files are maintained on disc by default\. This is useful for web applications that wish to inspect an \fIAccept\-Encoding\fR header and serve the appropriate file\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBcompress\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/compress\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake compress \-c [options\.\.\.] [files\.\.\.]
bake compress \-x [options\.\.\.] [files\.\.\.]
.
.fi
.
.SH "COMMANDS"
.
.TP
\fB\-c | create\fR:
.
.IP
Deflate file(s)\. This command creates a file with the same name as the source file appended with a \fBgz\fR file extension\. By default the original file is maintained, if you wish to overwrite the file(s) use the \fB\-\-overwrite\fR option\.
.
.TP
\fB\-x | extract\fR:
.
.IP
Inflate compressed file(s)\.
.
.SH "OPTIONS"
.
.TP
\fB\-d | \-\-delete\fR:
.
.IP
The default behaviour is to keep the source files, specify this flag if you wish to delete the source files\. This mimics the default behaviour of gzip(1) and gunzip(1) whereby source files are deleted when deflating and compressed files are deleted when inflating\.
.
.TP
\fB\-r | \-\-recursive\fR:
.
.IP
Recurse into sub\-directories\.
.
.TP
\fB\-\-noop\fR:
.
.IP
Do not perform any action, print information about the source and/or compressed files\. The \fB\-\-debug\fR option has no effect when this option is specified\.
.
.TP
\fB\-\-debug\fR:
.
.IP
Print the commands being executed\.
.
.SH "BUGS"
\fBtask\-compress\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBtask\-compress\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
