.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-LATEX" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-latex\fR \- latex task(s) for bake(1)
.
.SH "SYNOPSIS"
Latex task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Compile \fB\.tex\fR source files to \fB\.pdf\fR or \fB\.dvi\fR files\. When no options are specified this task searches the \fBdoc/latex\fR directory relative to the tasks(7) file and compiles all \fB\.tex\fR files found into \fB\.pdf\fR files within the \fB${target}\fR for the project\.
.
.P
Any option not recognised by this task is passed to pdflatex(1) so that you may set more advanced compilation options\.
.
.P
In addition, this task will change into the directory containing the source \fB\.tex\fR file so that graphics or any other external files can be resolved relative to the \fB\.tex\fR file without specifying \fB\egraphicspath\fR or other similar macros that may be required to resolve external files\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBlatex\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/latex\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake latex [pdf|dvi] [options\.\.\.] [files\.\.\.]
.
.fi
.
.SH "COMMANDS"
.
.TP
\fBpdf\fR:
.
.IP
Sets the output format to pdf\. This is the default output format used\.
.
.TP
\fBdvi\fR:
.
.IP
Sets the output format to dvi\.
.
.SH "OPTIONS"
.
.TP
\fB\-o | \-\-output [directory]\fR:
.
.IP
The output directory when compiling the source \fB\.tex\fR file(s)\.
.
.SH "FLAG OPTIONS"
.
.TP
\fB\-\-debug\fR:
.
.IP
Print the commands being executed\. If execution of pdflatex(1) fails with a >0 exit code then the contents of the compile log file are printed when this option is present\.
.
.SH "FILES"
Apart from the files generated by pdflatex(1) in the output directory, this task will create an additional file with the stdout and stderr output of calling pdflatex(1)\. The generated file is placed in the output directory and has the name of the source file (with the \.tex file extension removed) concatenated with \fB\.compile\.log\fR\. Note that we do not separate the stdout and stderr streams as all pdflatex(1) output is sent to stdout\.
.
.SH "DEPENDENCIES"
pdflatex(1), find(1)
.
.SH "BUGS"
This task does not support passing commands after the file specification to pdflatex(1)\.
.
.P
\fBtask\-latex\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBtask\-latex\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
