.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-TEST" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-test\fR \- unit test task(s) for bake(1)
.
.SH "SYNOPSIS"
Unit test task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Adds task methods for unit testing bash(1) programs, unit tests are defined in files with a \fB\.test\fR extension or as standalone executables with the \fBtest/bin\fR directory\.
.
.P
Binary tests (in \fBtest/bin\fR) are determined using the \fB\-x\fR file test flag therefore it is important to ensure you \fIdo not make files executable that are not test executables\fR\.
.
.SH "REQUIRE"
You do not need to require(3) this task as it is a builtin task\.
.
.SH "USAGE"
.
.nf

bake test [command] [suite:test\.\.\.]
.
.fi
.
.P
When no test suites are specified all test suites will be executed, otherwise pass a list of specific tests to run\. Note that when specifying the test suites you \fIdo not\fR include the \fB\.test\fR file extension\.
.
.SH "COMMANDS"
.
.TP
\fBrun\fR:
.
.IP
Run one or more test suites\.
.
.TP
\fBls\fR:
.
.IP
List test suites and test methods (if test methods have been specified)\. Use this command to test which test suites would be matched by the commands passed to task\-test(7)\.
.
.IP
If some tests have been excluded they are listed at the end with each test suite name preceeded by an exclamation mark \'!\'\.
.
.TP
\fBmake\fR:
.
.IP
Attempts to run a make(1) \fItest\fR target\.
.
.TP
\fBrake\fR:
.
.IP
Attempts to run a rake(1) \fItest\fR task\.
.
.TP
\fBant\fR:
.
.IP
Attempts to run an ant(1) \fItest\fR target\.
.
.TP
\fBmvn\fR:
.
.IP
Attempts to run a mvn(1) \fItest\fR goal\.
.
.SH "EXAMPLES"
These examples are based on the unit tests in the \fBtest\fR directory of the strike(7) repository\.
.
.P
The following commands are equivalent for running all tests:
.
.IP "" 4
.
.nf

bake test
bake test run
.
.fi
.
.IP "" 0
.
.P
Run an individual test suite:
.
.IP "" 4
.
.nf

bake test run json\.stringify
.
.fi
.
.IP "" 0
.
.P
Run a single method of a test suite:
.
.IP "" 4
.
.nf

bake test run json\.stringify:basic
.
.fi
.
.IP "" 0
.
.P
Note you omit the \fBtest\fR prefix as well as the test suite prefix \fBjson\.stringify\fR when referencing method names\.
.
.P
Run multiple methods of a test suite delimited by the colon \':\' character:
.
.IP "" 4
.
.nf

bake test run json\.stringify:basic:boolean
.
.fi
.
.IP "" 0
.
.P
It is an error condition to have a leading or trailing colon and the exit code will be >0 in this situation\.
.
.SH "FILES"
The \fBstdout\fR generated by unit tests is written to \fB${target}/test\.stdout\.log\fR whilst the \fBstderr\fR output from the unit tests is written to \fB${target}/test\.stderr\.log\fR\.
.
.SH "BUGS"
\fBtask\-test\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBtask\-test\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1), assert(7)
