.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-MVN" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-mvn\fR \- mvn task(s) for bake(1)
.
.SH "SYNOPSIS"
Integrates mvn(1) with bake(1)\.
.
.SH "DESCRIPTION"
A proxy for the mvn(1) executable, allows mvn(1) goals to be intermingled with bake(1) tasks\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBmvn\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/ext/build/mvn\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake mvn [options] [<goal(s)>] [<phase(s)>]
.
.fi
.
.SH "BUGS"
\fBtask\-mvn\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBtask\-mvn\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
