.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-TODO" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-todo\fR \- todo task(s) for bake(1)
.
.SH "SYNOPSIS"
Task(s) for bake(1) to find \fITODO\fR tags in a project\.
.
.SH "DESCRIPTION"
Adds task methods for scanning a project looking for \fITODO\fR tags, use these commands to give your code a sanity check\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBtodo\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/todo\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake todo [commands\.\.\.] [flags\.\.\.]
.
.fi
.
.SH "COMMANDS"
Command options for task\-todo(7)\.
.
.TP
\fBscan\fR:

.
.P
Scan the project \fB${root}\fR for files and print \fITODO\fR tags information\.
.
.P
The format of the output for each tag found is a comment line (preceeded by a \'#\' character and a single space) with the tag converted to uppercase followed by a space and then the file path concatenated with the line number using a \':\' delimiter, for example:
.
.IP "" 4
.
.nf

# TODO /path/to/project/bin/bake:358
this is a todo message string
.
.fi
.
.IP "" 0
.
.TP
\fBtags\fR:

.
.P
The \fBtags\fR command prints a list of tag identifiers and the corresponding pattern used to match a tag\.
.
.P
The output format for this command is an uppercase tag identifier delimited by the equals sign \'=\' followed by the pattern used to match the tag\.
.
.TP
\fBlist\fR:

.
.P
Use the \fBlist\fR command to print a list of the files that a scan would match\.
.
.TP
\fBexcludes\fR:

.
.P
Prints the exclude patterns\.
.
.SH "FLAGS"
Flag options for task\-todo(7)\.
.
.TP
\fB\-\-silent\fR:

.
.P
Makes task\-todo(7) mute, this is useful if you are only interested in the exit code\.
.
.SH "TAGS"
The following tags are supported by default:
.
.TP
\fBFIXME\fR:

.
.P
To mark potential problematic code that requires special attention and/or review\.
.
.TP
\fBTODO\fR:

.
.P
To indicate planned enhancements\.
.
.TP
\fBNOTE\fR:

.
.P
To document inner workings of code and indicate potential pitfalls\.
.
.TP
\fBXXX\fR:

.
.P
To warn other programmers of problematic or misguiding code\.
.
.TP
\fBCHANGED\fR:

.
.P
To indicate that behaviour or implementation has changed\.
.
.TP
\fBDEPRECATED\fR:

.
.P
To mark code as deprecated\.
.
.SH "EXIT CODES"
If any \fITODO\fR or \fIFIXME\fR tags are encountered then the program exits with a >0 exit code which is the total number of \fITODO\fR and \fIFIXME\fR tags found, otherwise 0\.
.
.SH "BUGS"
\fBtask\-todo\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBtask\-todo\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
