.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-TODO" "7" "January 2013" "" ""
.
.SH "NAME"
\fBtask\-todo\fR \- todo task(s) for bake(1)
.
.SH "SYNOPSIS"
Task(s) for bake(1) to find \fITODO\fR tags in a project\.
.
.SH "DESCRIPTION"
Adds task methods for scanning a project looking for \fITODO\fR tags, use these commands to give your code a sanity check\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBtodo\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/todo\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake todo [commands\.\.\.] [flags\.\.\.]
.
.fi
.
.SH "COMMANDS"
This section describes the command options for task\-todo(7)\. When no command is specified the default behaviour is to call the \fBscan\fR command\.
.
.TP
\fBscan\fR:

.
.P
Scan the project \fB${root}\fR for files and print \fITODO\fR tags information\.
.
.P
The format of the output for each tag found is a comment line (preceeded by a \'#\' character and a single space) with the tag converted to uppercase followed by a space and then the file path concatenated with the line number using a \':\' delimiter, for example:
.
.IP "" 4
.
.nf

# TODO /path/to/project/bin/bake:358
this is a todo message
.
.fi
.
.IP "" 0
.
.P
Output for \fIBUG\fR and \fIFIXME\fR tags found is redirected to stderr, all other tags found are sent to stdout\. This enables easy redirection of these tags to a file using a command such as:
.
.IP "" 4
.
.nf

bake todo scan 2> target/todo\.err\.log
.
.fi
.
.IP "" 0
.
.TP
\fBtags\fR:

.
.P
The \fBtags\fR command prints a list of tag identifiers and the corresponding pattern used to match a tag\.
.
.P
The output format for this command is an uppercase tag identifier delimited by the equals sign \'=\' followed by the pattern used to match the tag\.
.
.TP
\fBlist\fR:

.
.P
Use the \fBlist\fR command to print a list of the files that a scan would match\.
.
.TP
\fBcount\fR:

.
.P
Count occurences of tags, this implies the \fB\-\-silent\fR option\. The format of count output is an uppercase tag name and the count value delimited by an \'=\' character, for example:
.
.IP "" 4
.
.nf

TODO=76
.
.fi
.
.IP "" 0
.
.TP
\fBexcludes\fR:

.
.P
Prints the exclude patterns\.
.
.SH "OPTIONS"
Options for task\-todo(7)\.
.
.TP
\fB\-\-dir\fR:

.
.P
Add one or more directories \fIrelative to the project root\fR to scan for tags\. This removes all default directory scans and performs a custom scan using \fIonly\fR the directories specified on the command line\. For example:
.
.IP "" 4
.
.nf

bake todo scan \-\-dir bin \-\-dir src \-\-bug \-\-fixme
.
.fi
.
.IP "" 0
.
.TP
\fB\-\-file\fR:

.
.P
Add one or more files to the list of files to scan\.
.
.IP "" 4
.
.nf

bake todo scan \-\-file bin/bake
.
.fi
.
.IP "" 0
.
.P
If a file path starts with the pattern \'(\.+)?/\' then it will be treated as an absolute file path, otherwise the file is treated as relative to \fB${root}\fR\.
.
.SH "FLAGS"
Flag options for task\-todo(7)\.
.
.TP
\fB\-\-silent\fR:

.
.P
Makes task\-todo(7) mute, this is useful if you are only interested in the exit code\.
.
.SH "FILTER FLAGS"
You may specify any tag as an option to switch on tag filtering, when any filter tag option is specified, then only the tags specified are matched\. For example, to match only \fIBUG\fR tags, use:
.
.IP "" 4
.
.nf

bake todo scan \-\-bug
.
.fi
.
.IP "" 0
.
.P
But to include any other tags they must now be specified, so to find \fITODO\fR and \fINOTE\fR tags, use:
.
.IP "" 4
.
.nf

bake todo scan \-\-todo \-\-note
.
.fi
.
.IP "" 0
.
.TP
\fB\-\-bug\fR:

.
.P
Filter for \fIBUG\fR tag matches\.
.
.TP
\fB\-\-fixme\fR:

.
.P
Filter for \fIFIXME\fR tag matches\.
.
.TP
\fB\-\-todo\fR:

.
.P
Filter for \fITODO\fR tag matches\.
.
.TP
\fB\-\-note\fR:

.
.P
Filter for \fINOTE\fR tag matches\.
.
.TP
\fB\-\-xxx\fR:

.
.P
Filter for \fIXXX\fR tag matches\.
.
.TP
\fB\-\-changed\fR:

.
.P
Filter for \fICHANGED\fR tag matches\.
.
.TP
\fB\-\-deprecated\fR:

.
.P
Filter for \fIDEPRECATED\fR tag matches\.
.
.SH "TAGS"
The following tags are supported by default:
.
.TP
\fBBUG\fR:

.
.P
To mark a known bug\.
.
.TP
\fBFIXME\fR:

.
.P
To mark potential problematic code that requires special attention and/or review\.
.
.TP
\fBTODO\fR:

.
.P
To indicate planned enhancements\.
.
.TP
\fBNOTE\fR:

.
.P
To document inner workings of code and indicate potential pitfalls\.
.
.TP
\fBXXX\fR:

.
.P
To warn other programmers of problematic or misguiding code\.
.
.TP
\fBCHANGED\fR:

.
.P
To indicate that behaviour or implementation has changed\.
.
.TP
\fBDEPRECATED\fR:

.
.P
To mark code as deprecated\.
.
.SH "EXIT CODES"
If any \fIBUG\fR or \fIFIXME\fR tags are encountered then the program exits with a >0 exit code which is the total number of \fIBUG\fR and \fIFIXME\fR tags found, otherwise 0\.
.
.SH "DEPENDENCIES"
find(1)
.
.SH "BUGS"
\fBtask\-todo\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
\fBtask\-todo\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
