#!/usr/bin/env bash

#get absolute path to running script
name=`basename $0`;
abspath=$(cd ${BASH_SOURCE[0]%/*} && echo $PWD/${0##*/});
exedir=`dirname "$abspath"`;
libdir="$exedir/../lib";

#bring in the shared libraries
source "$libdir/shared";

function test_expansion {
	local relative="$1";
	expand_path "$relative";
	local expanded="$_result";
	if [ "$expanded" != "$relative" ]; then
		info "expanded %s to %s" "$relative" "$expanded";
	fi
}

git_ls_remote_tags "git@github.com:stax/server.git";
git_find_tag "non-existent-tag" "$_result";

if [ $? -eq 1 ]; then
	exit 1;
fi

exit 0;