#!/usr/bin/env bash

#get absolute path to running script
name=`basename $0`;
abspath=$(cd ${BASH_SOURCE[0]%/*} && echo $PWD/${0##*/});
exedir=`dirname "$abspath"`;
libdir="$exedir/../lib";

#bring in the shared libraries
source "$libdir/shared";

#attempt to copy the test runner to the /etc directory - should fail
expand_path "$exedir/../runner";
copy "$_result" "/etc";

if [ $? -ne 0 ]; then
	quit 1 "failed to copy file";
fi