#!/usr/bin/env bash

#get absolute path to running script
name=`basename $0`;
abspath=$(cd ${BASH_SOURCE[0]%/*} && echo $PWD/${0##*/});
exedir=`dirname "$abspath"`;
libdir="$exedir/../lib";

#bring in the shared libraries
source "$libdir/shared";

function test_expansion {
	local relative="$1";
	expand_path "$relative";
	local expanded="$_result";
	if [ "$expanded" != "$relative" ]; then
		info "expanded %s to %s" "$relative" "$expanded";
	fi
}

#expand a relative directory
test_expansion "$exedir/../";

#expand a file
test_expansion "$exedir/../runner";

success "expand path test complete";