#!/usr/bin/env bash

#get absolute path to running script
name=`basename $0`;
abspath=$(cd ${BASH_SOURCE[0]%/*} && echo $PWD/${0##*/});
exedir=`dirname "$abspath"`;
libdir="$exedir/../lib";

#bring in the shared libraries
source "$libdir/shared";

verifyshell;

success "shell verified as $TSHELL";