.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "REST" "1" "December 2012" "" ""
.
.SH "NAME"
\fBrest\fR \- Generate HTTP requests
.
.SH "SYNOPSIS"
\fBrest\fR command [\fIoptions\fR\.\.\.] \fIurl\fR
.
.br
.
.SH "DESCRIPTION"
\fBrest\fR generates HTTP requests using curl(1)\. The core commands correspond to the HTTP verbs GET, POST, PUT, HEAD, DELETE and OPTIONS\.
.
.SH "FILES"
The http(1) module generates some temporary files and some files used for logging purposes\.
.
.SH "OPTIONS"
Wherever possible \fBrest\fR follows the command line options available to curl(1) but also adds some convenient shortcut options\.
.
.IP "" 4
.
.nf

* `\-\-type`:
    Set the content type for the request\.
* `\-H`, `\-\-header`:
    Set a request header\.
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBrest\fR is written in bash and depends upon \fBbash\fR >= 4\.
.
.SH "COPYRIGHT"
rest is Copyright (C) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
manpages(5), curl(1)
