.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "REST" "1" "December 2012" "" ""
.
.SH "NAME"
\fBrest\fR \- Generate HTTP requests
.
.SH "SYNOPSIS"
\fBrest\fR command [\fIoptions\fR\.\.\.] \fIurl\fR
.
.br
.
.SH "DESCRIPTION"
\fBRest\fR generates HTTP requests using a command line format\. The core commands correspond to the HTTP verbs GET, POST, PUT, HEAD, DELETE and OPTIONS\.
