.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STRIKE\-TREE" "7" "January 2013" "" ""
.
.SH "NAME"
\fBstrike\-tree\fR \- filesystem structure for strike(7)
.
.SH "SYNOPSIS"
Although it is \fInot mandatory\fR it is recommended (for maximum portability and consistency) that you follow a convention for the filesystem structure which is shown below\.
.
.IP "" 4
.
.nf

|\-\- bin
|\-\- doc
|\-\- lib
|   |\-\- modules
|       |\-\- doc
|       |\-\- tasks
|\-\- man
|\-\- target
|\-\- test
.
.fi
.
.IP "" 0
.
.SH "BIN"
Executable files should be placed in the \fBbin\fR directory\.
.
.SH "DOC"
Auxiliary files for man page documentation (index\.html, index\.txt etc) should be placed in the \fBdoc\fR directory\.
.
.SH "LIB"
Library functions can be placed in the \fBlib\fR directory\. Note that files in this directory are not included when generating documentation using task\-doc(7), for inline documentation use a module\.
.
.SH "MODULES"
Modules for the program \fBmust\fR be in the \fBlib/modules\fR directory in order for require(3) to find your modules correctly when no relative or absolute path to the module has been specified\.
.
.SH "MODULES/DOC"
If you use \fB\.ronn\fR files in addition to the inline documentation functionality it is recommended that they are placed in \fBlib/modules/doc\fR\.
.
.SH "TASKS"
Any program\-specific tasks for bake(1) should be placed in \fBlib/modules/tasks\fR\.
.
.SH "MAN"
The \fBman\fR directory is where task\-doc(7) will place generated man pages\.
.
.SH "TARGET"
The \fBtarget\fR directory is used by bake(1) for staging, logging and any other temporary files, this directory should be ignored by any source code management tool such as git(1)\.
.
.SH "TEST"
Unit test files are searched for in the \fBtest\fR directory when task\-test(7) runs\.
.
.SH "SEE ALSO"
strike(7)
