.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ARRAY" "3" "April 2013" "" ""
.
.SH "NAME"
\fBarray\fR \- array module
.
.SH "SYNOPSIS"
Module commands for modifiying and inspecting arrays\.
.
.SH "BUGS"
\fBarray\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBarray\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
require(3)
