.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BOILERPLATE" "3" "April 2013" "" ""
.
.SH "NAME"
\fBboilerplate\fR \- boilerplate script
.
.SH "SYNOPSIS"
In order to resolve the executable path and library files the boilerplate script must be installed\. It performs the following functions:
.
.IP "\[ci]" 4
Resolve the full path to the executable resolving symbolic links
.
.IP "\[ci]" 4
Load the library functions
.
.IP "" 0
.
.SH "CODE"
The code to load the boilerplate script should be placed at the beginning of the executable:
.
.IP "" 4
.
.nf

boilerplate=$( command \-v boilerplate\.sh ) \e
    && \. "$boilerplate" && unset boilerplate \e
    || { echo "fatal: could not locate boilerplate\.sh" && exit 1; }
boilerplate "$@";
.
.fi
.
.IP "" 0
.
.SH "FILES"
The \fIboilerplate\.sh\fR file must be installed in PATH in order for executables to function correctly\.
.
.P
If you want the executables only available to a single user you can place the boilerplate\.sh file in a PATH directory for that user\. Whereas, if all users should be able to run the executables place the file in a common PATH directory such as /bin, /usr/bin or /usr/local/bin\.
.
.SH "NOTES"
The bake(1) executable needs to run under a few different situations including when \fIboilerplate\.sh\fR is not installed therefore it uses different logic for resolving the path to the script\.
.
.SH "COPYRIGHT"
\fBboilerplate\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
