.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BAKE" "1" "March 2013" "" ""
.
.SH "NAME"
\fBbake\fR \- make for bash
.
.SH "SYNOPSIS"
Delegates to task commands after setting a context\.
.
.SH "DESCRIPTION"
\fBbake\fR is \fBmake\fR for bash programs\. It provides an extensible system for managing project tasks using modular code\.
.
.SH "USAGE"
.
.nf

bake [task] [options\.\.\.]
.
.fi
.
.SH "OPTIONS"
The following options are parsed by bake(1), all other options are passed on to the task command\.
.
.TP
\fB\-v | \-\-verbose\fR:

.
.P
Set verbose mode for the task execution\.
.
.TP
\fB\-\-color=always|never|auto\fR:

.
.P
Define how ANSI escape sequences are generated, default is \fIauto\fR, see sprintf(3)\.
.
.TP
\fB\-\-version\fR:

.
.P
Print the program version and exit\.
.
.SH "BUILTIN TASKS"
All bake(1) projects have the following tasks built in:
.
.IP "\[ci]" 4
ls
.
.IP "\[ci]" 4
clean
.
.IP "" 0
.
.P
These commands will print more information if the \fB\-v | \-\-verbose\fR option is specified\.
.
.SH "REQUIRE TASKS"
The convention is that task commands are not declared in tasks(7) but are placed in modules and then included using require(3)\. So to include the semantic versioning functionality into your project all you need to do is require(3) it:
.
.IP "" 4
.
.nf

require tasks/semver;
.
.fi
.
.IP "" 0
.
.SH "FILES"
The bake(1) program looks for a tasks(7) file in the current working directory\. If no tasks(7) file is found in the current working directory then bake(1) will walk all parent directories looking for a tasks(7) file\.
.
.P
It maps commands (the first option passed to bake(1)) to a task command either builtin or declared (or required) by the tasks file\. A task is considered to be the first option passed to the \fBbake\fR executable, any other options specified on the command line are passed to the corresponding task command\.
.
.SH "VARIABLES"
The following variables are available to each task command:
.
.TP
\fBroot\fR:

.
.P
The directory where the \fBtasks\fR file is located\.
.
.TP
\fBproject_name\fR:

.
.P
The name of the project as determined by the name of the \fB${root}\fR directory\.
.
.TP
\fBproject\fR:

.
.P
This is the root of the project\. For most projects this will be equivalent to \fB${root}\fR but is useful for multi\-module projects where \fB${root}\fR points to the directory for the module and \fB${project}\fR is the root of the project\.
.
.TP
\fBproject_version\fR:

.
.P
The project version number, if no version information is available the value \fI0\.0\.0\fR is used\.
.
.TP
\fBtarget\fR:

.
.P
A staging directory corresponding to \fB${root}/target\fR\.
.
.TP
\fBtasks\fR:

.
.P
The file system path to the tasks file, eg: \fB${root}/tasks\fR\.
.
.TP
\fBtasks_file_name\fR:

.
.P
The name of the \fBtasks\fR file, if \fBbake_file_name\fR has been set this will equal that value, otherwise the default \fItasks\fR is used\.
.
.TP
\fBverbose\fR:

.
.P
Set to true if the \fB\-v | \-\-verbose\fR option was specified otherwise false\.
.
.SH "ENVIRONMENT"
.
.TP
\fBbake_file_name\fR:

.
.P
Determines the name of the file that bake(1) looks for to load task command methods from, default is \fItasks\fR\.
.
.TP
\fBbake_root\fR:

.
.P
Allows setting of the root directory for an execution\. This should be used with caution and is only made available for allowing file write during an execution of \fBmake distcheck\fR\.
.
.SH "EXIT CODES"
A >0 exit code is used when no task(7) file could be located or no command is available, otherwise the exit code is deferred to the task being executed\.
.
.TP
\fB1\fR:

.
.P
No task(7) file available in the current working directory (or any parent directories)\.
.
.TP
\fB2\fR:

.
.P
No task command available\.
.
.TP
\fB>0\fR:

.
.P
The task command invocation returned a non\-zero exit code but did not explicitly call \fBexit\fR\.
.
.P
It is recommended that task command implementations explicitly exit the program using the \fBquit\fR and \fBsuccess\fR sub\-commands declared by console(3)\.
.
.SH "BUGS"
\fBbake\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBbake\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
sprintf(3), console(3), task\-test(7), task\-doc(7), task\-clean(7), task\-ls(7), task\-semver(7)
