.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EXECUTABLE" "3" "March 2013" "" ""
.
.SH "NAME"
\fBexecutable\fR \- executable module
.
.SH "SYNOPSIS"
Module methods for system executables\.
.
.SH "DESCRIPTION"
Enables validation and referencing of executables in \fB$PATH\fR\.
.
.SH "USAGE"
Use executable(3) to validate a list of executables:
.
.IP "" 4
.
.nf

require \'executable\';
executable\.validate ronn git;
.
.fi
.
.IP "" 0
.
.P
If any of the listed executables are not available on the system the program will exit with a non\-zero exit code\. If executable validation succeeds the executable paths are available in the global \fBexecutables\fR associative array and can be accessed anywhere in the program, for example:
.
.IP "" 4
.
.nf

git\.find() {
    # will quit the program if git is not available
    executable\.validate git;
    local git="${executables[git]}";
    $git status;
}
git\.find;
.
.fi
.
.IP "" 0
.
.P
Sometimes it can be useful to test for an executable but do not quit the program so that the code can branch depending upon whether an executable is available (you have a fallback option)\. This can be achieved by passing the \fB\-\-test\fR flag as the \fIfirst\fR option to the validate command\.
.
.IP "" 4
.
.nf

git\.find() {
    # will be an empty string if git is not available
    executable\.validate \-\-test git;
    local git="${executables[git]}";
    if [ \-n "$git" ]; then
        $git status;
    else
        console info "git is not available";
        # implement fallback logic
    fi
}
git\.find;
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBexecutable\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBexecutable\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
require(3)
