.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PROMPT" "3" "March 2013" "" ""
.
.SH "NAME"
\fBprompt\fR \- user input module
.
.SH "SYNOPSIS"
.
.nf

prompt [command] [options\.\.\.]
.
.fi
.
.SH "DESCRIPTION"
Captures user input using \fBread\fR\.
.
.SH "COMMANDS"
.
.TP
\fBconfirm\fR:

.
.P
Capture a boolean response, this is useful for confirmation prompts\. By default, the values \fIyes\fR and \fIno\fR are used as the strings for comparison as to whether the confirmation was accepted or rejected\. Comparison is done in a case\-insensitive comparison on the first character of the received input\.
.
.P
If the input does not match an accept or reject value then the prompt is re\-displayed\.
.
.TP
\fBline\fR:

.
.P
Capture a non\-empty string value from a single line of input\. If the received line is empty then the prompt is re\-displayed\.
.
.TP
\fBselect\fR:

.
.P
Display a menu using the \fBselect\fR builtin\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-id=[identifier]\fR:

.
.P
Associate \fIid\fR with a prompt\.
.
.TP
\fB\-\-hist\-file=[file]\fR:

.
.P
Use \fIfile\fR for the history file\. If this option is not specified no history is maintained, if \fIfile\fR does not exist it is created\.
.
.TP
\fB\-\-before=[command]\fR:

.
.P
Execute \fIcommand\fR before reading input\.
.
.TP
\fB\-\-response=[command]\fR:

.
.P
Execute \fIcommand\fR when input is received\.
.
.TP
\fB\-\-acccepted=[command]\fR:

.
.P
Execute \fIcommand\fR when a confirm prompt is accepted\.
.
.TP
\fB\-\-rejected=[command]\fR:

.
.P
Execute \fIcommand\fR when a confirm prompt is rejected\.
.
.TP
\fB\-\-validate=[command]\fR:

.
.P
Execute \fIcommand\fR to validate a value, if the exit code of the command is greater than zero the prompt is re\-displayed\. The command is passed a single argument containing the value\.
.
.TP
\fB\-\-select\-error=[command]\fR:

.
.P
Execute \fIcommand\fR when a select menu receives input that is non\-numeric\.
.
.TP
\fB\-\-select\-range\-error=[command]\fR:

.
.P
Execute \fIcommand\fR when a select menu receives input that is numeric but falls outside of the range\.
.
.TP
\fB\-\-complete=[function]\fR:

.
.P
Execute \fIfunction\fR when the tab key is pressed to generate custom completion specifications\. This option is repeatable, functions are executed in declaration order\.
.
.P
When this option is not specified the default readline completion is used, otherwise the complete functions override the default behaviour\.
.
.TP
\fB\-\-timeout=[seconds]\fR:

.
.P
Use \fIseconds\fR as the prompt timeout\. If \fIseconds\fR is non\-numeric or zero it is ignored\. Equivalent to \fBread \-t\fR\.
.
.TP
\fB\-\-quit=[words]\fR:

.
.P
Use in conjunction with the \fB\-\-infinite\fR option to stop an infinite prompt if the entered value matches any word in \fIwords\fR\.
.
.TP
\fB\-\-default=[value]\fR:

.
.P
Use \fIvalue\fR when the user input is empty\. This option may be used to override the default behaviour of re\-displaying a prompt when no input is received\.
.
.TP
\fB\-s | \-\-silent\fR:

.
.P
Do not echo input\. Use this when capturing sensitive information such as passwords\. Equivalent to \fBread \-s\fR\.
.
.TP
\fB\-m | \-\-multiline\fR:

.
.P
Allow multiline input so that a backslash escape followed by a newline continues capturing data for a prompt\. Equivalent to \fBread \-r\fR\.
.
.TP
\fB\-e | \-\-exec\fR:

.
.P
Allow shell command execution\. When this option is present each line entered is executed as a shell command using \fBbash \-c\fR so that redirection, pipes and other more complex shell commands are possible\.
.
.TP
\fB\-i | \-\-infinite\fR:

.
.P
Show a prompt infinitely\. After a line has been read then the prompt is re\-displayed\.
.
.SH "BUGS"
\fBprompt\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBprompt\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
prompt(1), console(3)
