.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STRIKE" "7" "March 2013" "" ""
.
.SH "NAME"
\fBstrike\fR \- require for bash
.
.SH "SYNOPSIS"
Modular \fBbash\fR using require(3)\.
.
.SH "DESCRIPTION"
Brings structure and modularity to \fBbash\fR programs and provides a set of modules that can be used from any \fBbash\fR program\.
.
.SH "MODULES"
Once the library code has been included the following modules are automatically available to your code\.
.
.SS "method"
The method(3) module provides utility functions for determining whether functions exist, listing functions and removing methods\.
.
.SH "BUGS"
\fBstrike\fR is written in bash and depends upon \fBbash\fR >= 4\.2 for associative arrays\.
.
.SH "COPYRIGHT"
\fBstrike\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
strike\-tree(7), boilerplate(3)
