.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-DEVEL" "7" "March 2013" "" ""
.
.SH "NAME"
\fBtask\-devel\fR \- develelopment task(s) for bake(1)
.
.SH "SYNOPSIS"
Development task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Integrates with tasks\-project(7) to copy dependencies during local develelopment\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBdevel\fR task(s) using:
.
.IP "" 4
.
.nf

require \'tasks/devel\';
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake devel push [options\.\.\.] [id]
    bake devel pull [options\.\.\.] [id]
.
.fi
.
.SH "COMMANDS"
.
.TP
\fBpush\fR:
.
.IP "" 4
.
.nf

  Push this project to other project dependencies\.
.
.fi
.
.IP "" 0

.
.TP
\fBpull\fR:
.
.IP "" 4
.
.nf

  Pull project dependencies into this project\.
.
.fi
.
.IP "" 0

.
.SH "OPTIONS"
.
.TP
\fB\-\-force\fR:
.
.IP "" 4
.
.nf

  Force overwriting of an existing dependency\.
.
.fi
.
.IP "" 0

.
.TP
\fB\-\-test\fR:
.
.IP "" 4
.
.nf

  Run tests after a push or pull command\.
.
.fi
.
.IP "" 0

.
.TP
\fB\-\-revert\fR:
.
.IP "" 4
.
.nf

  Revert to the version in use prior to a push or pull if tests fails\.
.
.fi
.
.IP "" 0

.
.SH "BUGS"
\fBtask\-devel\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBtask\-devel\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1), tasks\-project(7)
