.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TASK\-COMPRESS" "7" "April 2013" "" ""
.
.SH "NAME"
\fBtask\-compress\fR \- compress task(s) for bake(1)
.
.SH "SYNOPSIS"
Compression task(s) for bake(1)\.
.
.SH "DESCRIPTION"
Deflate and inflate file(s) using gzip(1) and gunzip(1)\. This task is used to compress regular files, if you wish to compress directories use task\-archive(7)\. The primary difference between gzip(1) and task\-compress(7) is that source files or compressed files are maintained on disc by default\. This is useful for web applications that wish to inspect an \fIAccept\-Encoding\fR header and serve the appropriate file\.
.
.SH "REQUIRE"
In your tasks(7) file \fBrequire\fR the \fBcompress\fR task(s) using:
.
.IP "" 4
.
.nf

require tasks/compress;
.
.fi
.
.IP "" 0
.
.SH "USAGE"
.
.nf

bake compress \-c [options\|\.\|\.\|\.] [files\|\.\|\.\|\.]
bake compress \-x [options\|\.\|\.\|\.] [files\|\.\|\.\|\.]
.
.fi
.
.SH "COMMANDS"
.
.TP
\fB\-c | create\fR:
.
.IP
Deflate file(s)\. This command creates a file with the same name as the source file appended with a \fBgz\fR file extension\. By default the original file is maintained, if you wish to delete the file(s) use the \fB\-\-delete\fR option\.
.
.TP
\fB\-x | extract\fR:
.
.IP
Inflate compressed file(s)\.
.
.SH "OPTIONS"
.
.TP
\fB\-o | \-\-output [directory]\fR:
.
.IP
An existing writable directory to place files in\. When use in conjunction with the \fBcreate\fR command then the deflated files will be placed in this directory\. When used in conjunction with the \fBextract\fR command then the inflated files will be placed in this directory\. By default when this option is used the output is a flat structure, which means that if multiple files with the same name exist in the list of files being processed then the last one processed will overwrite any previously created file\.
.
.TP
\fB\-d | \-\-dir [directory]\fR:
.
.IP
The absolute path to the root directory where files are being resolved from\. Use in conjunction with the \fB\-\-output\fR and \fB\-\-recursive\fR option so that files may be created with a directory structure that matches the source directory structure\.
.
.TP
\fB\-i | \-\-include [pattern]\fR:
.
.IP
Pattern(s) that a file name must match to be included\. Must be a valid extended regular expression, see ere(7)\. Repeatable\. An exit code of 2 is used if a pattern is invalid\.
.
.TP
\fB\-e | \-\-exclude [pattern]\fR:
.
.IP
Pattern(s) that when matched against a file name will cause it to be excluded\. Must be a valid extended regular expression, see ere(7)\. Repeatable\. If include and exclude pattern(s) are specified that both match a file name the file will be excluded\. An exit code of 2 is used if a pattern is invalid\.
.
.SH "FLAG OPTIONS"
.
.TP
\fB\-r | \-\-recursive\fR:
.
.IP
Recurse into sub\-directories\. When this option is not specified and a directory is passed as a file then the contents of that directory are included in the list of files used for compression or extraction, but no sub\-directories will be searched\. Specify this option if you also wish to search sub\-directories for files to deflate/inflate\.
.
.TP
\fB\-v | \-\-verbose\fR:
.
.IP
Output more information\. When used in conjunction with the \fBcreate\fR and \fBextract\fR commands then this option will also include compression ratio information\. When specified in conjunction with the \fB\-\-noop\fR option the file size will be output after the file path\.
.
.TP
\fB\-\-delete\fR:
.
.IP
The default behaviour is to keep the source files, specify this flag if you wish to delete the source files\. This mimics the default behaviour of gzip(1) and gunzip(1) whereby source files are deleted when deflating and compressed files are deleted when inflating\.
.
.TP
\fB\-\-noop\fR:
.
.IP
Do not perform any action, print information about the source and/or compressed files\. The \fB\-\-debug\fR option has no effect when this option is specified\.
.
.TP
\fB\-\-debug\fR:
.
.IP
Print the commands being executed\. This option has no effect when the \fB\-\-noop\fR option is specified\.
.
.SH "STDIN"
You may use the \'\-\' convention to specify that the file list should be read from stdin\. For example to compress all the files in the current directory:
.
.IP "" 4
.
.nf

find \. \-depth 1 \-type f | bake compress \-c \-;
.
.fi
.
.IP "" 0
.
.P
In addition, you can combine reading a file list from stdin with files specified after the \'\-\', for example to compress all files with a \.css file extension in the \./css directory and a file named README in the current working directory:
.
.IP "" 4
.
.nf

find \./css \-depth 1 \-name *\.css | bake compress \-c \- README;
.
.fi
.
.IP "" 0
.
.SH "NOTES"
Any files specified that \fIdo not exist\fR are skipped from processing and a warning is printed\.
.
.P
When the \fBcreate\fR command is executed files that end in the \fB\.gz\fR file extension are automatically ignored\.
.
.SH "EXIT CODES"
A >0 exit code indicates failure while a 0 exit code indicates success\.
.
.P
If any file is encountered that is not a regular file (determined using the \-f file test operator) then the exit code is >0\.
.
.P
If an invalid pattern is specified using either the \-\-include or \-\-exclude option then an exit code of 2 is used\.
.
.SH "BUGS"
\fBtask\-compress\fR is written in bash and depends upon \fBbash\fR >= 4\.2\.
.
.SH "COPYRIGHT"
\fBtask\-compress\fR is copyright (c) 2012 muji \fIhttp://xpm\.io\fR
.
.SH "SEE ALSO"
bake(1)
