#!/usr/bin/env bash

######################################################################
# 	archive-utils
#
#	Utilties for working with the archives.
######################################################################

function extract_tar {
	local archive="$1";
	local target="$2";
	
	#change into the target directory for extraction
	if [ `pwd` != "$target" ]; then
		cdir "$target" > /dev/null;
	fi
	
	local name=`basename $archive`;
	local extension="${name##*.}";
	local opts;
	
	if [ "$extension" == "gz" ]; then
		opts="xzf";
	elif [ "$extension" == "bz2" ]; then
		opts="xjf";
	else
		quit 1 "invalid archive type found %s" "$extension";
	fi
	
	#extract the archive
	info "$EXTRACTING" "$opts" "$name" "$target";
	tar "$opts" "$archive" --directory="$target";
}

function create_tar {
	local archive="$1";
	local target="$2";
	
	local dir=`dirname "$target"`;
	local name=`basename "$target"`;
	
	#change into the target directory for extraction
	if [ `pwd` != "$dir" ]; then
		cdir "$dir" > /dev/null;
	fi
	
	info "$ARCHIVING" "$archive" "$target";
	
	#create the archive
	tar czf "$archive" "$name";
}