#!/usr/bin/env bash

######################################################################
# 	common
#
#	Common variables for all programs.
######################################################################

#keep track of the original working directory
OWD=$PWD;

#target shell that must be in use
TSHELL="bash";

DEFAULT_HOST="stax.net";
DB_HOST="db.${DEFAULT_HOST}";
DEFAULT_URL_SCHEME="https://";

WWW_URL="${DEFAULT_URL_SCHEME}www.${DEFAULT_HOST}";
DB_URL="${DEFAULT_URL_SCHEME}${DB_HOST}";

DB_AUTH_USER="appserver";

#the primary user name
USER_NAME="stax";

#the primary group name
GROUP_NAME="stax";

#full os specific type and host type
OS_INSTALL="$OSTYPE-$HOSTTYPE";

#darwin12-x86_64 == Mountain Lion (bash 3.2.48) ?
#darwin10.0-x86_64 == Snow Leopard (10.6.8) (bash 3.2.48)
#darwin10.8.0-i386 == Snow Leopard (10.6.8) (bash 4.2)

if [ "$OS_INSTALL" == "darwin12-x86_64" ] || [ "$OS_INSTALL" == "darwin10.8.0-i386" ];
	then OS_INSTALL="darwin10.0-x86_64";
fi

#darwin12-x86_64

#common paths
INSTALL_NAME="stax";

#the default environment used when installing
INSTALL_ENV="production";

DEFAULT_INSTALL_PREFIX="/usr/local";
DEFAULT_VAR_PREFIX="/usr/local/var";
DEFAULT_SRC_PREFIX="/usr/local/src";

#TODO: remove this duplication?
INSTALL_PATH="$DEFAULT_INSTALL_PREFIX";

BASE_PATH="$DEFAULT_INSTALL_PREFIX/$INSTALL_NAME";

#the name of the folder used to store user home directories
USERS_NAME="users";

#the name of the file used for user-specific path configuration
PATHS_CONF_NAME=".stax-paths.json";

#
USERS_HOME_PATH="$DEFAULT_VAR_PREFIX/$INSTALL_NAME/$USERS_NAME";

#common names used
BIN_NAME="bin";
SBIN_NAME="sbin";
VAR_NAME="var";
RUN_NAME="run";
LOG_NAME="log";
TMP_NAME="tmp";
LIB_NAME="lib";
DB_NAME="db";
CONF_NAME="conf";
APP_NAME="app";
PRIVATE_NAME="private";
PUBLIC_NAME="public";
KEYS_NAME="keys";
REPOS_NAME="repos";
STACK_NAME="stack";
STATIC_NAME="static";
SERVER_NAME="server";
WEBAPP_NAME="webapp";
DBTOOLS_NAME="dbtools";
DATA_NAME="data";
INSTALLERS_NAME="installers";
PREREQUISITES_NAME="prerequisites";
EXTRAS_NAME="extras";
MODULES_NAME="modules";
CERTS_NAME="certs";
SOCK_NAME="sock";
WWW_NAME="www";

COUCHDB_NAME="couchdb";
REDIS_NAME="redis";
NGINX_NAME="nginx";
NODE_NAME="node";

#core paths for installation
REPO_PATH="$BASE_PATH/$REPOS_NAME";
STACK_PATH="$BASE_PATH/$STACK_NAME";

#remote repositories
LIBRARY_REPO="git@github.com:stax/library.git";
STATIC_REPO="git@github.com:stax/static.git";
SERVER_REPO="git@github.com:stax/server.git";

#TODO: default tags to use for the various repositories
#STACK_TAG="dev-0.0.1";
#STATIC_TAG="dev-0.0.1";
#SERVER_TAG="dev-0.0.1";

LIBRARY_SUBMODULE_REPO_PATH="support/library";

#the private repository should be local for the moment
PRIVATE_REPO="$HOME/git/$INSTALL_NAME/$PRIVATE_NAME";

#name of the rc file
DROP_RC=".droprc";

#TODO: ensure these paths are reconfigured after a prefix is set once a --prefix argument is integrated

#preparation files
INSTALL_PRIVATE_PATH="$BASE_PATH/$PRIVATE_NAME";
INSTALL_BIN_PATH="$BASE_PATH/$BIN_NAME";
INSTALL_TMP_PATH="$BASE_PATH/$TMP_NAME";
INSTALL_DATA_PATH="$BASE_PATH/$DATA_NAME";
INSTALL_SBIN_PATH="$BASE_PATH/$SBIN_NAME";
INSTALL_VAR_PATH="$BASE_PATH/$VAR_NAME";
INSTALL_LOG_PATH="$INSTALL_VAR_PATH/$LOG_NAME";
INSTALL_DB_PATH="$DEFAULT_VAR_PREFIX/$DB_NAME";
INSTALL_DB_REDIS_PATH="$INSTALL_DB_PATH/$REDIS_NAME";
INSTALL_DB_COUCHDB_PATH="$INSTALL_DB_PATH/$COUCHDB_NAME";
INSTALL_LOG_INSTALLERS_PATH="$INSTALL_LOG_PATH/$INSTALLERS_NAME";
INSTALL_RUN_PATH="$INSTALL_VAR_PATH/$RUN_NAME";
INSTALL_CONF_PATH="$INSTALL_VAR_PATH/$CONF_NAME";
INSTALL_PUBLIC_PATH="$BASE_PATH/$PUBLIC_NAME";

INSTALL_STATIC_PATH="$BASE_PATH/$STATIC_NAME";

CONSOLE_PLIST="$INSTALL_DATA_PATH/plist/com.stax.console.plist";

#web application modules
INSTALL_SERVER_PATH="$BASE_PATH/$SERVER_NAME";
INSTALL_WEBAPP_PATH="$INSTALL_SERVER_PATH/$WEBAPP_NAME";
INSTALL_DBTOOLS_PATH="$INSTALL_SERVER_PATH/$DBTOOLS_NAME";

#pid files for application servers
INSTALL_APP_RUN_PATH="$INSTALL_RUN_PATH/$APP_NAME";
INSTALL_APP_SOCK_PATH="$INSTALL_RUN_PATH/$SOCK_NAME";

#symlink for the current configuration
INSTALL_CONF_SYM_LINK="$BASE_PATH/$CONF_NAME";

#root settings
ROOT_USER="root";

#node settings
NODE_USER="stax-app";
INSTALL_NODE_CONF_PATH="$INSTALL_PRIVATE_PATH/$APP_NAME/$CONF_NAME";

#nginx settings
NGINX_USER="stax-www";
NGINX_PID_FILE="$INSTALL_RUN_PATH/${NGINX_NAME}.pid";
NGINX_CERTS="$INSTALL_PRIVATE_PATH/$CERTS_NAME/$NGINX_NAME";

#redis settings
REDIS_USER="stax-db";
REDIS_PID_FILE="$INSTALL_RUN_PATH/${REDIS_NAME}.pid";
REDIS_LOG="$INSTALL_LOG_PATH/redis.log";
REDIS_CONF="$INSTALL_CONF_SYM_LINK/redis.conf";

#couchdb settings
COUCHDB_USER="stax-db";
COUCHDB_PID_FILE="$INSTALL_RUN_PATH/${COUCHDB_NAME}.pid";
COUCHDB_STD_OUT_LOG="$INSTALL_LOG_PATH/${COUCHDB_NAME}.stdout.log";
COUCHDB_STD_ERR_LOG="$INSTALL_LOG_PATH/${COUCHDB_NAME}.stderr.log";
COUCHDB_DIR="$INSTALL_DB_PATH/couchdb";
COUCHDB_LOG="$INSTALL_LOG_PATH/couch.log";
#path to couchdb configuration files
COUCHDB_CONFIG_PATH="$INSTALL_CONF_SYM_LINK/$COUCHDB_NAME";
COUCHDB_CONFIG_ADMINS_PATH="$INSTALL_PRIVATE_PATH/$DB_NAME/$COUCHDB_NAME/admins.ini";