#!/usr/bin/env bash

######################################################################
# 	common
#
#	Common variables for all programs.
######################################################################

#keep track of the original working directory
OWD=$PWD;

#target shell that must be in use
TSHELL="bash";

#full os specific type and host type
OS_INSTALL="$OSTYPE-$HOSTTYPE";

#darwin12-x86_64 == Mountain Lion (bash 3.2.48) ?
#darwin10.0-x86_64 == Snow Leopard (10.6.8) (bash 3.2.48)
#darwin10.8.0-i386 == Snow Leopard (10.6.8) (bash 4.2)

if [ "$OS_INSTALL" == "darwin12-x86_64" ] || [ "$OS_INSTALL" == "darwin10.8.0-i386" ];
	then OS_INSTALL="darwin10.0-x86_64";
fi

#darwin12-x86_64