#!/usr/bin/env bash

######################################################################
# 	messages
#
#	Variables containing program messages.
######################################################################

#cleaning
CLEANING="cleaning %s";
CLEAN_COMPLETE="clean complete";

#tests
TEST_PREFIX="[test]";
TEST_FAIL="[fail]";
TEST_PASS="[pass]";
TEST_RUNNER_START="running tests in %s";
TEST_RUN_START="%s started on %s expects %s";
TEST_RUN_STATUS="%s program %s exited with code %s";
TEST_RUN_FAIL="%s failed test %s with code %s expected %s";
TEST_RUN_PASS="%s finished test on %s with code %s";

#fs
CHECK_DIRECTORY="checking if %s is a directory";
CREATED_DIRECTORY="mkdir -p %s";
DIRECTORY_CREATE_FAIL="could not create directory %s";
CHANGED_DIRECTORY="pwd %s";
DIRECTORY_CHANGE_FAIL="could not change working directory to %s";

REMOVED_DIRECTORY="rm -rf %s";
DIRECTORY_REMOVE_FAIL="could not delete directory %s";

SUDO_REMOVED_DIRECTORY="sudo rm -rf %s";
SUDO_DIRECTORY_REMOVE_FAIL="could not delete directory %s using sudo";

COPY_SUCCESS="cp -rf %s > %s";
COPY_ERROR="cp -rf %s > %s";

MOVE_SUCCESS="mv %s > %s";
MOVE_ERROR="mv %s > %s";

SYM_LINK_SUCCESS="ln -s %s > %s";
SYM_LINK_ERROR="ln -s %s > %s";

PROGRAM_NOT_FOUND="%s not found";

#install
PLATFORM_INSTALL_CHECK="checking for %s install";
PLATFORM_INSTALL_PASS="found %s install directory";
PLATFORM_INSTALL_FAIL="unsupported platform %s";

PROGRAM_INSTALL_CHECK="checking for %s install on %s";
PROGRAM_INSTALL_RUN="%s installing %s from %s";

INSTALL_SOURCE_PATH_MISSING="installation source path not specified";
INSTALL_SOURCE_PATH_INVALID="installation source path is not valid";

INSTALL_FULL_NAME_MISSING="installation full name not specified";
INSTALL_SHORT_NAME_MISSING="installation short name not specified";

#install program start up data
INSTALL_START_MSG="installing %s from source %s";

#archive
EXTRACTING="tar %s %s > %s";
EXTRACTION_ERROR="could not extract archive %s";

ARCHIVING="tar czf %s < %s";